if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/install_manifest.txt")
    message(FATAL_ERROR "Cannot find install manifest: ${CMAKE_CURRENT_BINARY_DIR}/install_manifest.txt")
endif()

file(READ "${CMAKE_CURRENT_BINARY_DIR}/install_manifest.txt" files)
string(REPLACE "\n" ";" files "${files}")
foreach(file ${files})
    if(EXISTS "${file}")
        message(STATUS "Removing ${file}")
        file(REMOVE "${file}")
    endif()
endforeach()

# Remove empty directories created during installation
set(prefixes ${CMAKE_INSTALL_PREFIX})
foreach(dir IN LISTS prefixes)
    if(EXISTS ${dir})
        message(STATUS "Pruning empty directories under ${dir}")
        file(GLOB_RECURSE subdirs LIST_DIRECTORIES true ${dir}/*)
        list(SORT subdirs DESCENDING)
        foreach(subdir ${subdirs})
            if(IS_DIRECTORY ${subdir})
                file(GLOB children ${subdir}/*)
                if(children STREQUAL "")
                    file(REMOVE_RECURSE ${subdir})
                endif()
            endif()
        endforeach()
    endif()
endforeach()
